config/routes.rb
Rails.application.routes.draw do

  resources :images

  get 'probar', to: 'control#saludo'

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/control_controller.rb
class ControlController < ApplicationController

  def saludo
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new image_params
    @image.save

    redirect_to @image
  end

  def show
  end

  def edit
  end

  def update
    @image.update image_params
    redirect_to @image
  end

  def destroy
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:description)
  end

  def set_image
    @image = Image.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/control/saludo.html.erb
<p>Hola desde el controlador :D </p>

app/views/images/_form.html.erb
<div class="form-group">
  <%= form_for @image do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>
  </br>
  <%= f.submit 'Enviar', class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-md-6">
  <figure class="figure">
    <img src="https://getuikit.com/v2/docs/images/placeholder_600x400.svg" class="figure-img img-fluid rounded">
    <figcaption class="figure-caption"><%= image.description %>.
      <%= link_to 'Edit', edit_image_path(image) %>
      <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'sure?'}  %>
    </figcaption>
  </figure>
</div>

app/views/images/edit.html.erb
<div class="container">
  <p>Edit Images :D</p>
  <%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <%= render @images %>
  </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <p>Hola desde mi vista new (Images) :D</p>

  <%= render 'form' %>
</div>

app/views/images/show.html.erb
<!-- <p>Image Saved</p> -->
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>